version: "3"

services:

  backend:
    build: ./food-ordering-backend
    env_file:
      - ./food-ordering-backend/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rfom
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo

  frontend:
    build: ./food-ordering-frontend
    ports:
      - "5173:5173"
    restart: always

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"