export const cuisineList = [
  "Biryani",
  "Butter Chicken",
  "Chaat",
  "Chinese-Indian",
  "Chole Bhature",
  "Coastal",
  "Desserts",
  "Dosa",
  "Drinks & Juices",
  "Fried Rice",
  "Gujarati",
  "Hyderabadi",
  "Ice Cream",
  "Idli",
  "Kebab",
  "Kerala",
  "Kulcha & Naan",
  "Mughlai",
  "North Indian",
  "Paneer",
  "Paratha",
  "Pizza",
  "Punjabi",
  "Rajasthani",
  "South Indian",
  "Street Food",
  "Tandoori",
  "Thali",
  "Vegan",
  "Vegetarian",
];
